#!/usr/bin/env python3
"""Generate docs/reference/variables.md from settings.py via settings-doc."""

from __future__ import annotations

import subprocess
from pathlib import Path

BANNER = (
    "<!-- AUTOGENERATED FROM src/aws_eks_helm_deploy/settings.py — "
    "DO NOT EDIT BY HAND. "
    "Regenerate via `uv run scripts/generate-variables-doc.py`. -->\n\n"
)
OUT = Path("docs/reference/variables.md")
# fmt: off
CMD = ["uv", "run", "--extra", "docs", "settings-doc", "generate",
       "--class", "aws_eks_helm_deploy.settings.Settings",
       "--output-format", "markdown"]
# fmt: on


def main() -> int:
    result = subprocess.run(CMD, capture_output=True, text=True, check=True)
    OUT.write_text(BANNER + result.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
