"""Structural tests for the variable reference generator (Plan 07-03, DOC-02 SC-2).

Asserts:
  - scripts/generate-variables-doc.py exists and is ≤30 LOC (NIH-free wrapper invariant).
  - docs/reference/variables.md starts with the D5 autogenerated banner.
  - pyproject.toml pins settings-doc == 4.3.2 in [project.optional-dependencies] docs.
  - scripts/check-variables-drift.sh exists and is executable.
  - Running the generator produces no drift against the committed file (integration-style;
    skipped when uv is unavailable in the test environment).
"""

from __future__ import annotations

import os
import pathlib
import shutil
import subprocess

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GEN_SCRIPT = REPO_ROOT / "scripts" / "generate-variables-doc.py"
DRIFT_SCRIPT = REPO_ROOT / "scripts" / "check-variables-drift.sh"
VARS_DOC = REPO_ROOT / "docs" / "reference" / "variables.md"
PYPROJECT = REPO_ROOT / "pyproject.toml"

BANNER_PREFIX = "<!-- AUTOGENERATED FROM src/aws_eks_helm_deploy/settings.py — DO NOT EDIT BY HAND."


def test_generate_variables_doc_script_exists() -> None:
    """The generator script must exist at scripts/generate-variables-doc.py."""
    assert GEN_SCRIPT.is_file(), f"Expected {GEN_SCRIPT} to be a file"


def test_generate_variables_doc_script_at_most_30_lines() -> None:
    """Generator must remain a thin wrapper (≤30 LOC) — enforces NIH-free invariant."""
    line_count = len(GEN_SCRIPT.read_text().splitlines())
    assert line_count <= 30, f"Generator exceeds 30 LOC cap: {line_count} lines"


def test_docs_reference_variables_md_starts_with_banner() -> None:
    """variables.md must begin with the D5 autogenerated banner to prevent hand edits."""
    content = VARS_DOC.read_text()
    assert content.startswith(BANNER_PREFIX), (
        f"Expected variables.md to start with banner prefix:\n  {BANNER_PREFIX!r}\n"
        f"Got first 200 chars:\n  {content[:200]!r}"
    )


def test_pyproject_pins_settings_doc_4_3_2() -> None:
    """pyproject.toml must pin settings-doc to 4.3.2 in [project.optional-dependencies] docs."""
    pyproject_text = PYPROJECT.read_text()
    assert '"settings-doc == 4.3.2"' in pyproject_text, (
        'Expected `"settings-doc == 4.3.2"` in pyproject.toml'
    )


def test_check_variables_drift_script_exists_and_executable() -> None:
    """scripts/check-variables-drift.sh must exist and be executable."""
    assert DRIFT_SCRIPT.is_file(), f"Expected {DRIFT_SCRIPT} to be a file"
    assert os.access(DRIFT_SCRIPT, os.X_OK), f"Expected {DRIFT_SCRIPT} to be executable"


def test_running_generator_produces_no_drift_against_committed_file() -> None:
    """Running the generator must not drift against the committed variables.md.

    Skipped if `uv` is unavailable (e.g. minimal CI lanes that don't sync docs extras).
    """
    if shutil.which("uv") is None:
        pytest.skip("uv not available — drift check is exercised by the docs-drift CI job")

    before = VARS_DOC.read_text()
    try:
        subprocess.run(
            ["uv", "run", "--extra", "docs", "python", "scripts/generate-variables-doc.py"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except subprocess.CalledProcessError as exc:
        pytest.fail(f"Generator failed: stdout={exc.stdout!r} stderr={exc.stderr!r}")

    after = VARS_DOC.read_text()
    assert before == after, (
        "Drift detected: regenerating variables.md changed the file. "
        "Re-run `uv run --extra docs python scripts/generate-variables-doc.py` and commit."
    )
